port = 8080
# port = 8443
https = false
# @TODO how to import `pkg/frontend.js` with enabled cache busting?
# @TODO add a switch to enable Typescript generator in mzoon?
cache_busting = false
backend_log_level = "warn" # "error" / "warn" / "info" / "debug" / "trace"

[redirect]
port = 8081
enabled = false

[cors]
origins = ["*"]

[watch]
frontend = [
    "public",
    "frontend/Cargo.toml",
    "frontend/src",
    "frontend/typescript/bundles",
    "shared/Cargo.toml",
    "shared/src",
]
backend = [
    "backend/Cargo.toml",
    "backend/src",
    "backend/index.js",
    "backend/style.css",
]
