[build]
# `target` to to prevent rebuilding from scratch on each change
[target.wasm32-unknown-unknown]
# https://docs.rs/web-sys/latest/web_sys/struct.Window.html#method.show_open_file_picker
# https://github.com/rustwasm/wasm-bindgen/issues/2339#issuecomment-1000651386
rustflags = ["--cfg=web_sys_unstable_apis"]
